branches:
  only:
    - master

language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=3.7.11
    - php: 5.6
      env: WP_VERSION=trunk

before_install:
  - phpenv config-rm xdebug.ini
  - composer validate

install:
  - pecl channel-update pecl.php.net
  - printf "\n" | pecl install imagick
  - composer install
  - bash bin/install-package-tests.sh

script:
  - bash bin/test.sh
